name: Environment indicator
type: module
description: Adds a color indicator for the different environments.
package: Development
core: 8.x

scripts:
  - environment_indicator.js
  - color.js

stylesheets:
  all:
    - environment_indicator.css

configure: environment_indicator.list