drupal.environment_indicator:
  version: '2.0'
  js:
    js/environment_indicator.js: {}
    js/color.js: {}
  css:
    component:
      css/environment_indicator.css: {}
  dependencies:
    - color/drupal.color