environment_indicator_list:
  pattern: '/admin/config/development/environment-indicator'
  defaults:
    _entity_list: 'environment_indicator'
  requirements:
    _permission: 'administer taxonomy'

environment_indicator_delete:
  pattern: '/admin/config/development/environment-indicator/{environment_indicator}/delete'
  defaults:
    _entity_form: 'environment_indicator.delete'
  requirements:
    _entity_access: 'environment_indicator.delete'

environment_indicator_update:
  pattern: '/admin/config/development/environment-indicator/{environment_indicator}'
  defaults:
    _entity_form: 'environment_indicator'
  requirements:
    _entity_access: 'environment_indicator.update'
