environment_indicator.list:
  path: '/admin/config/development/environment-indicator'
  defaults:
    _entity_list: 'environment_indicator'
    _title: 'Environment Indicators List'
  requirements:
    _permission: 'administer environment indicator settings'

environment_indicator.delete:
  path: '/admin/config/development/environment-indicator/manage/{environment_indicator}/delete'
  defaults:
    _entity_form: 'environment_indicator.delete'
  requirements:
    _entity_access: 'environment_indicator.delete'

environment_indicator.update:
  path: '/admin/config/development/environment-indicator/manage/{environment_indicator}'
  defaults:
    _entity_form: 'environment_indicator'
  requirements:
    _entity_access: 'environment_indicator.update'

environment_indicator.add:
  path: '/admin/config/development/environment-indicator/add'
  defaults:
    _entity_form: 'environment_indicator'
  requirements:
    _entity_create_access: 'environment_indicator'

environment_indicator.settings:
  path: '/admin/config/development/environment-indicator/settings'
  defaults:
    _form: '\Drupal\environment_indicator\Form\EnvironmentIndicatorSettingsForm'
  requirements:
    _permission: 'administer environment indicator settings'