# Schema for the configuration files of the Block module.

environment_indicator.environment_indicator.*:
  type: config_entity
  label: 'Environment Indicator'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: string
      label: 'Label'
    weight:
      type: integer
      label: 'Weight'
    regexurl:
      type: string
      label: 'RegexURL'
    color:
      type: string
      label: 'Color'
    position:
      type: string
      label: 'Position'
    fixed:
      type: boolean
      label: 'Weight'
    disabled:
      type: boolean
      label: 'fixed'

#environment_indicator.settings.*:
 # type: environment_indicator_settings