name: environment_indicator_default
description: 'Default environment.'
human_name: 'Default environment'
disabled: true
text: 'DEFAULT ENVIRONMENT'
color: '#A33'
weight: 99
position: top
fixed: 0
regexurl: '.*'